<?php
$z[0]=Array("global","",31,56);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("field","",515,538);
$z[1][4]['name']="id";
$z[2]=Array("global","",1004,1036);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1197,1229);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1388,1420);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("php","\r\n								for (\$i = 1; \$i < 12; \$i++)\r\n								{\r\n                                    \$isecheck = (\$i == 1) ? 'checked=\"1\" ' : '';\r\n								    echo '<li><input type=\"radio\" name=\"face\" value=\"'.\$i.'\" '.\$isecheck.'/><img src=\"'.\$cfg_templets_skin.'/images/mood/ico-mood-'.\$i.'.gif\" /></li>';\r\n								}\r\n								",1646,1979);
$z[6]=Array("global","",2555,2581);
$z[6][4]['name']="cfg_cmspath";
$z[7]=Array("php","\r\n								if(\$cfg_mb_open=='Y') {\r\n              		echo '<script language=\"javascript\" type=\"text/javascript\">CheckLogin();</script>';\r\n              	}\r\n							",2898,3080);
$z[8]=Array("field","",3489,3516);
$z[8][4]['name']="phpurl";
$z[9]=Array("field","",3534,3550);
$z[9][4]['name']="id";
$z[10]=Array("global","",4187,4212);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("global","",4357,4383);
$z[11][4]['name']="cfg_phpurl";
$z[12]=Array("field","",4421,4437);
$z[12][4]['name']="id";
$z[13]=Array("global","",4777,4802);
$z[13][4]['name']="cfg_cmsurl";
$z[14]=Array("global","",5732,5760);
$z[14][4]['name']="cfg_soft_lang";
$z[15]=Array("field","",5826,5842);
$z[15][4]['name']="id";
$z[16]=Array("global","",6185,6210);
$z[16][4]['name']="cfg_phpurl";
$z[17]=Array("global","",6349,6374);
$z[17][4]['name']="cfg_cmsurl";

?>